# Currency Exchange with API in Python

### Packages

In [ ]:
%%cmd
pip install requests
pip install pandas
pip install plotly.express
pip install nbformat
pip install nbconvert

### Imports

In [1]:
from datetime import datetime, date, timedelta
import time
import requests
import pandas as pd
import plotly.express as px
import plotly.io as pio

### Constants

In [2]:
backdating_weeks = 52
base = "EUR"
quote = "CHF"
base_value = 100
quote_value = 100

pio.renderers.default = "notebook_connected"

### Calculating Start Date

In [3]:
start_date_list = str(datetime.now() - timedelta(weeks = backdating_weeks))
start_date = start_date_list.split(" ")[0]

### API

In [4]:
url_base_quote = "https://api.frankfurter.dev/v2/rates?base="+base+"&from="+start_date+"&quotes="+quote
url_quote_base = "https://api.frankfurter.dev/v2/rates?base="+quote+"&from="+start_date+"&quotes="+base

### Overview Of Fetched Data

In [5]:
response_base_quote = requests.get(url_base_quote)
response_quote_base = requests.get(url_quote_base)

data_base_quote = response_base_quote.json()
data_quote_base = response_quote_base.json()

print(data_base_quote)
print(data_quote_base)

[{'date': '2025-04-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93041}, {'date': '2025-04-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93325}, {'date': '2025-04-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93605}, {'date': '2025-04-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94001}, {'date': '2025-04-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94261}, {'date': '2025-04-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94288}, {'date': '2025-04-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94288}, {'date': '2025-04-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9426}, {'date': '2025-04-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93973}, {'date': '2025-04-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93938}, {'date': '2025-05-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93815}, {'date': '2025-05-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93623}, {'date': '2025-05-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93583}, {'date': '2025-05-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93582}, {'date': '2025-05-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93524}, {'date': '2025-05-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93481}, {'date': '2025-05-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93538}, {'date': '2025-05-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93493}, {'date': '2025-05-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93492}, {'date': '2025-05-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93521}, {'date': '2025-05-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93521}, {'date': '2025-05-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93651}, {'date': '2025-05-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93767}, {'date': '2025-05-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93905}, {'date': '2025-05-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93934}, {'date': '2025-05-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93797}, {'date': '2025-05-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93796}, {'date': '2025-05-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93796}, {'date': '2025-05-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93851}, {'date': '2025-05-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9384}, {'date': '2025-05-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93629}, {'date': '2025-05-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93495}, {'date': '2025-05-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93394}, {'date': '2025-05-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93375}, {'date': '2025-05-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93375}, {'date': '2025-05-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93556}, {'date': '2025-05-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93774}, {'date': '2025-05-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93676}, {'date': '2025-05-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93694}, {'date': '2025-05-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93414}, {'date': '2025-05-31', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93409}, {'date': '2025-06-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93404}, {'date': '2025-06-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93419}, {'date': '2025-06-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.935}, {'date': '2025-06-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93615}, {'date': '2025-06-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93772}, {'date': '2025-06-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93758}, {'date': '2025-06-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93769}, {'date': '2025-06-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93769}, {'date': '2025-06-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93714}, {'date': '2025-06-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93792}, {'date': '2025-06-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94067}, {'date': '2025-06-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94193}, {'date': '2025-06-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93872}, {'date': '2025-06-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.938}, {'date': '2025-06-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.938}, {'date': '2025-06-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93853}, {'date': '2025-06-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9399}, {'date': '2025-06-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94025}, {'date': '2025-06-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93932}, {'date': '2025-06-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9399}, {'date': '2025-06-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94032}, {'date': '2025-06-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94034}, {'date': '2025-06-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93968}, {'date': '2025-06-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93906}, {'date': '2025-06-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9372}, {'date': '2025-06-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93716}, {'date': '2025-06-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93746}, {'date': '2025-06-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93715}, {'date': '2025-06-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93715}, {'date': '2025-06-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93647}, {'date': '2025-07-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93365}, {'date': '2025-07-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93377}, {'date': '2025-07-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93471}, {'date': '2025-07-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93485}, {'date': '2025-07-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93483}, {'date': '2025-07-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93483}, {'date': '2025-07-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93509}, {'date': '2025-07-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93612}, {'date': '2025-07-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93345}, {'date': '2025-07-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93311}, {'date': '2025-07-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9314}, {'date': '2025-07-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93126}, {'date': '2025-07-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93126}, {'date': '2025-07-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93096}, {'date': '2025-07-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93159}, {'date': '2025-07-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93236}, {'date': '2025-07-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93207}, {'date': '2025-07-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93258}, {'date': '2025-07-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93261}, {'date': '2025-07-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93264}, {'date': '2025-07-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93287}, {'date': '2025-07-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93347}, {'date': '2025-07-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93274}, {'date': '2025-07-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93297}, {'date': '2025-07-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93553}, {'date': '2025-07-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93553}, {'date': '2025-07-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93553}, {'date': '2025-07-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93492}, {'date': '2025-07-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93281}, {'date': '2025-07-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93037}, {'date': '2025-07-31', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92977}, {'date': '2025-08-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93025}, {'date': '2025-08-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93045}, {'date': '2025-08-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93045}, {'date': '2025-08-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93343}, {'date': '2025-08-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93491}, {'date': '2025-08-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93621}, {'date': '2025-08-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93938}, {'date': '2025-08-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94182}, {'date': '2025-08-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94178}, {'date': '2025-08-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94178}, {'date': '2025-08-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94177}, {'date': '2025-08-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94232}, {'date': '2025-08-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94234}, {'date': '2025-08-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9419}, {'date': '2025-08-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94198}, {'date': '2025-08-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94209}, {'date': '2025-08-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9421}, {'date': '2025-08-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94298}, {'date': '2025-08-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94157}, {'date': '2025-08-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.94066}, {'date': '2025-08-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93942}, {'date': '2025-08-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93978}, {'date': '2025-08-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93968}, {'date': '2025-08-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93968}, {'date': '2025-08-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93959}, {'date': '2025-08-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93866}, {'date': '2025-08-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93556}, {'date': '2025-08-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93508}, {'date': '2025-08-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93642}, {'date': '2025-08-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93656}, {'date': '2025-08-31', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93656}, {'date': '2025-09-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93698}, {'date': '2025-09-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93718}, {'date': '2025-09-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93721}, {'date': '2025-09-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93807}, {'date': '2025-09-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93919}, {'date': '2025-09-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93918}, {'date': '2025-09-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93918}, {'date': '2025-09-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93488}, {'date': '2025-09-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93342}, {'date': '2025-09-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93352}, {'date': '2025-09-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9342}, {'date': '2025-09-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93466}, {'date': '2025-09-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93469}, {'date': '2025-09-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93469}, {'date': '2025-09-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93491}, {'date': '2025-09-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93431}, {'date': '2025-09-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93388}, {'date': '2025-09-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93376}, {'date': '2025-09-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93464}, {'date': '2025-09-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93482}, {'date': '2025-09-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93483}, {'date': '2025-09-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93594}, {'date': '2025-09-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9359}, {'date': '2025-09-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93438}, {'date': '2025-09-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.934}, {'date': '2025-09-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93413}, {'date': '2025-09-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93398}, {'date': '2025-09-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93398}, {'date': '2025-09-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9343}, {'date': '2025-09-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93566}, {'date': '2025-10-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93607}, {'date': '2025-10-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93645}, {'date': '2025-10-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93572}, {'date': '2025-10-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93563}, {'date': '2025-10-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93563}, {'date': '2025-10-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93399}, {'date': '2025-10-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93124}, {'date': '2025-10-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93075}, {'date': '2025-10-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93115}, {'date': '2025-10-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93305}, {'date': '2025-10-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93315}, {'date': '2025-10-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93315}, {'date': '2025-10-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93202}, {'date': '2025-10-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93081}, {'date': '2025-10-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93056}, {'date': '2025-10-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92933}, {'date': '2025-10-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92687}, {'date': '2025-10-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92632}, {'date': '2025-10-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92632}, {'date': '2025-10-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92494}, {'date': '2025-10-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92386}, {'date': '2025-10-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92319}, {'date': '2025-10-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92508}, {'date': '2025-10-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9255}, {'date': '2025-10-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92556}, {'date': '2025-10-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92558}, {'date': '2025-10-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92684}, {'date': '2025-10-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92652}, {'date': '2025-10-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9273}, {'date': '2025-10-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92832}, {'date': '2025-10-31', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9288}, {'date': '2025-11-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92881}, {'date': '2025-11-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92881}, {'date': '2025-11-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92966}, {'date': '2025-11-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93011}, {'date': '2025-11-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93037}, {'date': '2025-11-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93164}, {'date': '2025-11-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93206}, {'date': '2025-11-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93203}, {'date': '2025-11-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93203}, {'date': '2025-11-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93264}, {'date': '2025-11-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93091}, {'date': '2025-11-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92673}, {'date': '2025-11-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92442}, {'date': '2025-11-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92161}, {'date': '2025-11-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.921}, {'date': '2025-11-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.921}, {'date': '2025-11-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92221}, {'date': '2025-11-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92333}, {'date': '2025-11-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92663}, {'date': '2025-11-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92968}, {'date': '2025-11-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92973}, {'date': '2025-11-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92976}, {'date': '2025-11-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92983}, {'date': '2025-11-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93031}, {'date': '2025-11-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93353}, {'date': '2025-11-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93482}, {'date': '2025-11-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93451}, {'date': '2025-11-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93313}, {'date': '2025-11-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93292}, {'date': '2025-11-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93292}, {'date': '2025-12-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93309}, {'date': '2025-12-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93433}, {'date': '2025-12-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93486}, {'date': '2025-12-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9347}, {'date': '2025-12-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93534}, {'date': '2025-12-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93564}, {'date': '2025-12-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93564}, {'date': '2025-12-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93765}, {'date': '2025-12-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9381}, {'date': '2025-12-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93752}, {'date': '2025-12-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93576}, {'date': '2025-12-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93336}, {'date': '2025-12-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93335}, {'date': '2025-12-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93335}, {'date': '2025-12-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93543}, {'date': '2025-12-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93522}, {'date': '2025-12-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93507}, {'date': '2025-12-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.9335}, {'date': '2025-12-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93331}, {'date': '2025-12-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93321}, {'date': '2025-12-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93319}, {'date': '2025-12-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93181}, {'date': '2025-12-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93015}, {'date': '2025-12-24', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92888}, {'date': '2025-12-25', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92849}, {'date': '2025-12-26', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92856}, {'date': '2025-12-27', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92863}, {'date': '2025-12-28', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92863}, {'date': '2025-12-29', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92944}, {'date': '2025-12-30', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92925}, {'date': '2025-12-31', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93099}, {'date': '2026-01-01', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93147}, {'date': '2026-01-02', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93064}, {'date': '2026-01-03', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93048}, {'date': '2026-01-04', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93053}, {'date': '2026-01-05', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93006}, {'date': '2026-01-06', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92877}, {'date': '2026-01-07', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93096}, {'date': '2026-01-08', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93089}, {'date': '2026-01-09', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93173}, {'date': '2026-01-10', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93178}, {'date': '2026-01-11', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93178}, {'date': '2026-01-12', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93219}, {'date': '2026-01-13', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93172}, {'date': '2026-01-14', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93342}, {'date': '2026-01-15', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93332}, {'date': '2026-01-16', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93195}, {'date': '2026-01-17', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93192}, {'date': '2026-01-18', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93192}, {'date': '2026-01-19', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.93071}, {'date': '2026-01-20', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92803}, {'date': '2026-01-21', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92742}, {'date': '2026-01-22', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92878}, {'date': '2026-01-23', 'base': 'EUR', 'quote': 'CHF', 'rate': 0.92843}, {'date': '20

### Adding Data To Pandas DataFrame

In [6]:
df_base_quote = pd.DataFrame(data_base_quote)
df_quote_base = pd.DataFrame(data_quote_base)

In [7]:
df_base_quote

           date base quote     rate
0    2025-04-21  EUR   CHF  0.93041
1    2025-04-22  EUR   CHF  0.93325
2    2025-04-23  EUR   CHF  0.93605
3    2025-04-24  EUR   CHF  0.94001
4    2025-04-25  EUR   CHF  0.94261
..          ...  ...   ...      ...
360  2026-04-16  EUR   CHF  0.92331
361  2026-04-17  EUR   CHF  0.92263
362  2026-04-18  EUR   CHF  0.92265
363  2026-04-19  EUR   CHF  0.92267
364  2026-04-20  EUR   CHF  0.92067

[365 rows x 4 columns]

In [8]:
df_quote_base

           date base quote    rate
0    2025-04-21  CHF   EUR  1.0748
1    2025-04-22  CHF   EUR  1.0716
2    2025-04-23  CHF   EUR  1.0684
3    2025-04-24  CHF   EUR  1.0639
4    2025-04-25  CHF   EUR  1.0610
..          ...  ...   ...     ...
360  2026-04-16  CHF   EUR  1.0830
361  2026-04-17  CHF   EUR  1.0838
362  2026-04-18  CHF   EUR  1.0838
363  2026-04-19  CHF   EUR  1.0838
364  2026-04-20  CHF   EUR  1.0848

[365 rows x 4 columns]

### Plot Charts

In [9]:
px.line(df_base_quote, x = "date", y = "rate", title = f"{quote}/{base} Exchange Rate", labels = {"date": "Date", "rate": "Exchange Rate"}, height = 600, width = 1000)

In [10]:
px.line(df_quote_base, x = "date", y = "rate", title = f"{base}/{quote} Exchange Rate", labels = {"date": "Date", "rate": "Exchange Rate"}, height = 600, width = 1000)

### Calculating Example

In [11]:
print(f"The current exchange rate is: {df_base_quote["rate"].iloc[-1]:.4f} {quote} per {base}")
print(f"Within the last {backdating_weeks} weeks, the exchange rate has been between {df_base_quote["rate"].min():.4f} and {df_base_quote["rate"].max():.4f}")
print(f"The average exchange rate within the last {backdating_weeks} weeks was {df_base_quote["rate"].mean():.4f}")
print(f"This means that {base_value} {base} is worth {quote_value * df_base_quote["rate"].iloc[-1]:.4f} {quote}")

The current exchange rate is: 0.9207 CHF per EUR
Within the last 52 weeks, the exchange rate has been between 0.9027 and 0.9430
The average exchange rate within the last 52 weeks was 0.9296
This means that 100 EUR is worth 92.0670 CHF

In [12]:
print(f"The current exchange rate is: {df_quote_base["rate"].iloc[-1]} {base} per {quote}")
print(f"Within the last {backdating_weeks} weeks, the exchange rate has been between {df_quote_base["rate"].min()} and {df_quote_base["rate"].max()}")
print(f"The average exchange rate within the last {backdating_weeks} weeks was {df_quote_base["rate"].mean():.3f}")
print(f"This means that {quote_value} {quote} is worth {base_value * df_quote_base["rate"].iloc[-1]:.4f} {base}")

The current exchange rate is: 1.0848 EUR per CHF
Within the last 52 weeks, the exchange rate has been between 1.0604 and 1.1076
The average exchange rate within the last 52 weeks was 1.076
This means that 100 CHF is worth 108.4800 EUR

### Export Documentation

In [ ]:
%%cmd
jupyter nbconvert --to html currencyexchange.ipynb